### ISSUE TITLE
Error during installation!

### ISSUE THREAD

**Issue by madhavtummala** [apsknight/acl#1]
madhavtummala OpenSource $ python3 -m pip install -e git://github.com/apsknight/acl.git@0.1#egg=acl
```
Obtaining acl from git+git://github.com/apsknight/acl.git@0.1#egg=acl
  Cloning git://github.com/apsknight/acl.git (to revision 0.1) to ./src/acl
Requirement already satisfied: Click in /usr/local/lib/python3.7/site-packages (from acl) (7.0)
Requirement already satisfied: robobrowser in /usr/local/lib/python3.7/site-packages (from acl) (0.5.3)
Requirement already satisfied: bs4 in /usr/local/lib/python3.7/site-packages (from acl) (0.0.1)
Requirement already satisfied: tabulate in /usr/local/lib/python3.7/site-packages (from acl) (0.8.2)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.7/site-packages (from robobrowser->acl) (1.11.0)
Requirement already satisfied: beautifulsoup4>=4.3.2 in /usr/local/lib/python3.7/site-packages (from robobrowser->acl) (4.6.3)
Requirement already satisfied: Werkzeug>=0.10.4 in /usr/local/lib/python3.7/site-packages (from robobrowser->acl) (0.14.1)
Requirement already satisfied: requests>=2.6.0 in /usr/local/lib/python3.7/site-packages (from robobrowser->acl) (2.20.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/site-packages (from requests>=2.6.0->robobrowser->acl) (3.0.4)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.7/site-packages (from requests>=2.6.0->robobrowser->acl) (1.24.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/site-packages (from requests>=2.6.0->robobrowser->acl) (2018.11.29)
Requirement already satisfied: idna<2.8,>=2.5 in /usr/local/lib/python3.7/site-packages (from requests>=2.6.0->robobrowser->acl) (2.7)
Installing collected packages: acl
  Found existing installation: acl 0.1
    Uninstalling acl-0.1:
      Successfully uninstalled acl-0.1
  Running setup.py develop for acl
Successfully installed acl
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/pip/__main__.py", line 19, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/__init__.py", line 310, in main
    return command.main(cmd_args)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/basecommand.py", line 180, in main
    timeout=min(5, options.timeout)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/basecommand.py", line 77, in _build_session
    insecure_hosts=options.trusted_hosts,
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/download.py", line 337, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/download.py", line 126, in user_agent
    setuptools_version = get_installed_version("setuptools")
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 832, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 554, in __init__
    self.add_entry(entry)
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 610, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1876, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1395, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1750, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1627, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1584, in load
    mtime = os.stat(path).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/site-packages/acl-0.1-py3.7.egg'
```
Looks like it installed, but why the error?

**Comment by apsknight** [comment]
Hi @MadhavChoudhary 

I didn't find this error on fresh installation. Could you please tell how to reproduce this error?

**Comment by apsknight** [comment]
@MadhavChoudhary I've updated the install instruction(https://github.com/apsknight/acl/blob/master/README.md#install). Could you please check if this fix the issue for you.

**Comment by madhavtummala** [comment]
Thanks, it is fixed now.
