### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by madhavtummala** [apsknight/acl#2]
madhavtummala OpenSource $ acl
```
Roll Number: 16CS01041
Password:
Traceback (most recent call last):
  File "/usr/local/bin/acl", line 11, in <module>
    load_entry_point('acl', 'console_scripts', 'acl')()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/madhavtummala/Documents/OpenSource/src/acl/source/cli.py", line 13, in attendance
    response = attempt(roll, password)
  File "/Users/madhavtummala/Documents/OpenSource/src/acl/source/scrapper.py", line 9, in attempt
    form['email'].value = user
TypeError: 'NoneType' object is not subscriptable
```
This is happening irrespective of whether the password is correct or incorrect.

**Comment by apsknight** [comment]
Thanks for opening the issue.

I couldn't reproduce the error after fresh installation. Could you please reinstall and check if you are still getting the error.

**Comment by madhavtummala** [comment]
Works now, Thanks.
